### ISSUE TITLE
Trace back when running run_me.py

### ISSUE THREAD

**Issue by phil2008** [PacktPublishing/Mastering-Big-Data-Analytics-with-PySpark#19]
I am running an Ubuntu 20.04 LTS host on VMWARE.  Check the Readme and requirements.   All the modules have been installed.   Python version (from conda - 4.9.2) is 3.8.5

Trying to execute the run_me.py script, but getting the following errors

(base) phil@ubuntu:~/Project/Mastering-Big-Data-Analytics-with-PySpark-master (3)/Mastering-Big-Data-Analytics-with-PySpark-master$ python run_me.py
INFO     CourseHandler        Welcome to 'Mastering Big Data Analytics with Pyspark' by Danny Meijer <chilltake@gmail.com>
INFO     CourseHandler        Course Version: 20200420
INFO     CourseHandler        Course Name: Mastering Big Data Analytics with Pyspark
INFO     CourseHandler        Container Name: mastering-pyspark-ml
INFO     CourseHandler        Downloading the data
INFO     CourseHandler        Processing Sentiment140TrainingData
INFO     CourseHandler        Directory "sentiment-140-training-data" already exists
INFO     CourseHandler        Skipping "trainingandtestdata.zip"
INFO     CourseHandler        Processing MovieLens-Small
INFO     CourseHandler        Directory "ml-latest-small" already exists
INFO     CourseHandler        Skipping "ml-latest-small.zip"
INFO     CourseHandler        Processing MovieLens
INFO     CourseHandler        Directory "ml-latest" already exists
INFO     CourseHandler        Skipping "ml-latest.zip"
INFO     CourseHandler        Connecting to Docker API
Traceback (most recent call last):
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/phil/Downloads/yes/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_me.py", line 324, in <module>
    course = Course()
  File "run_me.py", line 114, in __init__
    self._client()
  File "run_me.py", line 152, in _client
    self.client = docker.from_env()
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/phil/Downloads/yes/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by dannymeijer** [comment]
Seems like an issue with the way your docker is set up. Please verify your docker settings.
- try starting the docker container manually
- verify that docker python library is installed correctly in your environment
- alternatively, just use jupyter (lab) through Anaconda (avoiding docker)
