### ISSUE TITLE
run_me.py: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by oserttas-math** [PacktPublishing/Mastering-Big-Data-Analytics-with-PySpark#3]
Hi I was trying to run `python run_me.py` command as suggested in the README, however ended up having a bit long, hard to understand error messages. I use `pipenv` and created a pyhton3.6.5 environment for this course.

Please help me decipher the following issues:

(ozkans) ozkans@OZKANs-MacBook-Pro Mastering-Big-Data-Analytics-with-PySpark % python --version
Python 3.6.5
(ozkans) ozkans@OZKANs-MacBook-Pro Mastering-Big-Data-Analytics-with-PySpark % python run_me.py
INFO     CourseHandler        Welcome to 'Mastering Big Data Analytics with Pyspark' by Danny Meijer <chilltake@gmail.com>
INFO     CourseHandler        Course Version: 20200420
INFO     CourseHandler        Course Name: Mastering Big Data Analytics with Pyspark
INFO     CourseHandler        Container Name: mastering-pyspark-ml
INFO     CourseHandler        Downloading the data
INFO     CourseHandler        Processing Sentiment140TrainingData
INFO     CourseHandler        Directory "sentiment-140-training-data" already exists
INFO     CourseHandler        Skipping "trainingandtestdata.zip"
INFO     CourseHandler        Processing MovieLens-Small
INFO     CourseHandler        Directory "ml-latest-small" already exists
INFO     CourseHandler        Skipping "ml-latest-small.zip"
INFO     CourseHandler        Processing MovieLens
INFO     CourseHandler        Directory "ml-latest" already exists
INFO     CourseHandler        Skipping "ml-latest.zip"
INFO     CourseHandler        Connecting to Docker API
Traceback (most recent call last):
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/api/client.py", line 205, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/api/client.py", line 228, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_me.py", line 329, in <module>
    course = Course()
  File "run_me.py", line 113, in __init__
    self._client()
  File "run_me.py", line 153, in _client
    self.client = docker.from_env()
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/api/client.py", line 188, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/ozkans/.local/share/virtualenvs/ozkans-QsBVdfJX/lib/python3.6/site-packages/docker/api/client.py", line 213, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by dannymeijer** [comment]
Hey there,

Seems like a problem with the VirtualEnv. Please confirm that the
requirements.txt is installed in the environment by running pip install -r
requirements.txt.
It could also be related to the docker API - but not quite sure. What OS is
this being run on?

Kind regards
Danny Meijer

**Comment by dannymeijer** [comment]
Did you ever get it to work OK? @oserttas-math
